export const SET_ACTIVE_DEVICE_PROPERTIES = "SET_ACTIVE_DEVICE_PROPERTIES";
export const SET_ACTIVE_DEVICE_INFO = "SET_ACTIVE_DEVICE_INFO";

export const SET_CONFIG = "SET_CONFIG";
export const SET_ACTIVE_BUTTON_INDEX = "SET_ACTIVE_BUTTON_INDEX";
export const SET_BUTTON = "SET_BUTTON";
